export const moviesData = [

    {   id : '1',
    image : 'https://m.media-amazon.com/images/M/MV5BNzI5MjUyYTEtMTljZC00NGI5LWFhNWYtYjY0ZTQ5YmEzMWRjXkEyXkFqcGdeQXVyMTY3MDE5MDY1._V1_FMjpg_UX1000_.jpg',
    rating :5,
    name : 'The Walking Dead',
    date :'2010',
    type : 'Drama,Horror',
    season :'11',
    description :'Based on the comic book series written by Robert Kirkman, this gritty drama portrays life in the months and years that follow a zombie apocalypse. .'
},
{   id : '2',
    image : 'https://i.ebayimg.com/images/g/18gAAOSwDgRkx3KB/s-l400.jpg',
    rating :5,
    name : 'Banshee',
    date :'2013',
    type : 'Action',
    season :'4',
    description :' The series centers on an enigmatic ex-con and master thief who assumes the identity of Lucas Hood, sheriff of the corrupt small town of Banshee.'
},
{   id : '3',
    image : 'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p186698_b_v9_ay.jpg',
    rating :4.5,
    name : 'Sons Of Anarchy',
    date :'2008',
    type : 'Action',
    season :'7',
    description :'Set in the fictional town of Charming, California, the series follows the story of Jackson "Jax" Teller (Charlie Hunnam), the vice president of the Sons of Anarchy Motorcycle Club Redwood Original (SAMCRO).'
},
{   id : '4',
    image : 'https://images.justwatch.com/poster/272744917/s718/marvels-the-punisher.jpg',
    rating :4,
    name : 'The Punisher',
    date :'2017',
    type : 'Action',
    season :'2',
    description :'is an American vigilante action-thriller film based on the Marvel Comics character of the same name, directed by Jonathan Hensleigh, who also co-wrote the screenplay with Michael Franzese.'
},
{   id : '5',
    image : 'https://fr.web.img5.acsta.net/pictures/17/05/22/16/49/588696.jpg',
    rating :4.5,
    name : 'Prison Break',
    date :'2005',
    type : 'Drama',
    season :'5',
    description :'series revolves around two brothers: Lincoln Burrows (Dominic Purcell), who has been convicted of murdering the Vice President of the United States, and Michael Scofield (Wentworth Miller).'
},
{   id : '6',
    image : 'https://static.tvtropes.org/pmwiki/pub/images/screenshot_2023_08_30_at_16_21_31_ems_3jpg_webp_image_1400_2100_pixels_scaled_35.png',
    rating :3,
    name : 'Breaking Bad',
    date :'2008',
    type : 'Drama',
    season :5,
    description :'a chemistry teacher who turns to producing and selling methamphetamine with a former student named Jesse Pinkman (Aaron Paul), after being diagnosed with stage-three lung cancer.'
},
]